// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/gummymule/task-manager/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: task
func (_m *TaskRepository) Create(task *domain.Task) (*domain.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Task) (*domain.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*domain.Task) *domain.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id, userID
func (_m *TaskRepository) Delete(id int64, userID int64) error {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: userID, boardID, page, limit
func (_m *TaskRepository) FindAll(userID int64, boardID int64, page int, limit int) ([]domain.Task, error) {
	ret := _m.Called(userID, boardID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64, int, int) ([]domain.Task, error)); ok {
		return rf(userID, boardID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, int64, int, int) []domain.Task); ok {
		r0 = rf(userID, boardID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64, int, int) error); ok {
		r1 = rf(userID, boardID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id, userID
func (_m *TaskRepository) FindByID(id int64, userID int64) (*domain.Task, error) {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) (*domain.Task, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) *domain.Task); ok {
		r0 = rf(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: task
func (_m *TaskRepository) Update(task *domain.Task) (*domain.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Task) (*domain.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*domain.Task) *domain.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
